# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schedule.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eschedule.proto\"\xee\x01\n\x08Schedule\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\t\x12#\n\x08subjects\x18\x02 \x03(\x0b\x32\x11.Schedule.Subject\x1a\xaf\x01\n\x07Subject\x12\x13\n\x0bsubjectName\x18\x01 \x01(\t\x12\x11\n\tbeginTime\x18\x02 \x01(\t\x12\x0f\n\x07\x65ndTime\x18\x03 \x01(\t\x12\x13\n\x0bweekNumbers\x18\x04 \x03(\x05\x12\x12\n\nauditorium\x18\x05 \x01(\t\x12\r\n\x05place\x18\x06 \x01(\t\x12\x12\n\nisEvenWeek\x18\x07 \x01(\x08\x12\x0f\n\x07teacher\x18\x08 \x01(\t\x12\x0e\n\x06\x66ormat\x18\t \x01(\t')



_SCHEDULE = DESCRIPTOR.message_types_by_name['Schedule']
_SCHEDULE_SUBJECT = _SCHEDULE.nested_types_by_name['Subject']
Schedule = _reflection.GeneratedProtocolMessageType('Schedule', (_message.Message,), {

  'Subject' : _reflection.GeneratedProtocolMessageType('Subject', (_message.Message,), {
    'DESCRIPTOR' : _SCHEDULE_SUBJECT,
    '__module__' : 'schedule_pb2'
    # @@protoc_insertion_point(class_scope:Schedule.Subject)
    })
  ,
  'DESCRIPTOR' : _SCHEDULE,
  '__module__' : 'schedule_pb2'
  # @@protoc_insertion_point(class_scope:Schedule)
  })
_sym_db.RegisterMessage(Schedule)
_sym_db.RegisterMessage(Schedule.Subject)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCHEDULE._serialized_start=19
  _SCHEDULE._serialized_end=257
  _SCHEDULE_SUBJECT._serialized_start=82
  _SCHEDULE_SUBJECT._serialized_end=257
# @@protoc_insertion_point(module_scope)
